### ISSUE TITLE
bug: crashes if PV output is on a different line

### ISSUE THREAD

**Issue by uwuplant** [Disservin/fast-chess#93]
if an engine outputs its PV on a different line than the other stats, then fast-chess crashes.

```
#0  0x00007ffff7a61ee7 in ?? () from /usr/lib/libc.so.6
#1  0x0000555555599132 in fast_chess::Tournament::parseEngineOutput(fast_chess::Board const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, long) const [clone .constprop.0] ()
```

**Comment by PGG106** [comment]
the problem is at line 528 of tournament.cpp, where we assume score depth and nodes to be present in the second to last output line, this results in accesses to invalid indexes and generates some faulty behaviour, a temporary hotfix (that comes with the downside of incorrect pgn reporting for any engine that splits the output) will soon be published

**Comment by PGG106** [comment]
to actually address this problem we need
1) For the findElement function to check if the element exists at all and for the absence of an element to be accounted for
2) To expand the parsing beyond assuming the data is on the second to last line

**Comment by Disservin** [comment]
Also the uci protocol says that there should be a final info report before bestmove in one line.
so I my opinion we do not need to parse this scenario however it should not cause a crash
https://backscattering.de/chess/uci/#engine-bestmove-info

**Comment by PGG106** [comment]
there is a final info report, the problem is the info is incomplete, cutechess does somehow handle this

**Comment by PGG106** [comment]
solved in #97
